name: academic_activities_mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.1.1
  share_plus: ^10.0.2
  url_launcher: ^6.2.6
  google_fonts: ^6.3.2
  font_awesome_flutter: ^10.12.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  dio: ^5.9.0
  intl: ^0.20.2
  flutter_spinkit: ^5.2.0
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  cached_network_image: ^3.3.1
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_svg: ^2.0.7
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
  assets:
    - assets/images/
    - assets/images/home/
    - assets/images/patterns/
    - assets/images/avatars/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png" # Giữ nguyên nếu file tên là logo.png
  min_sdk_android: 21
  adaptive_icon_background: "#003366" # Thêm dòng này (rất quan trọng!)
  adaptive_icon_foreground: "assets/icon/logo.png" # Thêm dòng này (bắt buộc Android 8+)
