name: academic_activities_mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.1.1
  share_plus: ^10.0.2
  url_launcher: ^6.2.6
  google_fonts: ^6.3.2
  font_awesome_flutter: ^10.12.0
  dio: ^5.9.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_svg: ^2.0.7

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
  assets:
    - assets/images/
    - assets/images/home/
    - assets/images/patterns/
    - assets/images/avatars/
    - assets/icons/
